<?php

if($modtopag != "adm") die("check the module you want to pag");

 $arr_all_files = array();

 $arr_all_files[]="xxxxx"; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                


?>
