<?php

	$role_info[382] = array (
  'code' => 'goal-dev',
  'name' => 
  array (
    'ar' => 'إعدادات القبول',
    'en' => 'Admission settings',
  ),
  'menu' => 
  array (
    'need_admin' => false,
    'id' => '382',
    'menu_name_' => 'إعدادات القبول',
    'menu_name_ar' => 'إعدادات القبول',
    'menu_name_en' => 'Admission settings',
    'page' => 'main.php?Main_Page=fm.php&a=1282&r=382',
    'css' => 'info',
    'icon' => ' icon-382',
    'showme' => true,
    'items' => 
    array (
      104643 => 
      array (
        'id' => '104643',
        'code' => 'f2-a-acondition_origin/qsearch',
        'level' => '999',
        'menu_name_ar' => 'القرارات و اللوائح',
        'menu_name_en' => 'Regulations',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AconditionOrigin&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104643 bfc-',
      ),
      104636 => 
      array (
        'id' => '104636',
        'code' => 'f2-a-acondition/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الشروط',
        'menu_name_en' => 'Conditions',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Acondition&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104636 bfc-',
      ),
      104650 => 
      array (
        'id' => '104650',
        'code' => 'f2-a-aparameter/qsearch',
        'level' => '999',
        'menu_name_ar' => 'القيم المعلمة',
        'menu_name_en' => 'Parameters',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Aparameter&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104650 bfc-',
      ),
      104685 => 
      array (
        'id' => '104685',
        'code' => 'f2-a-academic_year/qsearch',
        'level' => '999',
        'menu_name_ar' => 'السنوات الدراسية',
        'menu_name_en' => 'Academic years',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AcademicYear&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104685 bfc-',
      ),
      104699 => 
      array (
        'id' => '104699',
        'code' => 'f2-a-application_model/qsearch',
        'level' => '999',
        'menu_name_ar' => 'نماذج القبول',
        'menu_name_en' => 'Application models',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ApplicationModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104699 bfc-',
      ),
      104723 => 
      array (
        'id' => '104723',
        'code' => 'f2-a-application_plan/qsearch',
        'level' => '999',
        'menu_name_ar' => 'خطط التقديم',
        'menu_name_en' => 'Application plans',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ApplicationPlan&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104723 bfc-',
      ),
      104800 => 
      array (
        'id' => '104800',
        'code' => 'f2-a-api_endpoint/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الخدمات الاكترونية',
        'menu_name_en' => 'Api endpoints',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ApiEndpoint&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104800 bfc-',
      ),
      104793 => 
      array (
        'id' => '104793',
        'code' => 'f2-a-app_model_api/qsearch',
        'level' => '999',
        'menu_name_ar' => 'خدمات نماذج التقديم',
        'menu_name_en' => 'App model apis',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AppModelApi&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104793 bfc-',
      ),
      104807 => 
      array (
        'id' => '104807',
        'code' => 'f2-a-application_field/qsearch',
        'level' => '999',
        'menu_name_ar' => 'حقول البيانات',
        'menu_name_en' => '???? ????????',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ApplicationField&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104807 bfc-',
      ),
      104815 => 
      array (
        'id' => '104815',
        'code' => 'f2-a-screen_model/qsearch',
        'level' => '999',
        'menu_name_ar' => 'شاشات الإدخال',
        'menu_name_en' => 'Screen models',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ScreenModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104815 bfc-',
      ),
    ),
    'otherbfs' => 
    array (
      104631 => 
      array (
        'id' => '104631',
        'code' => 'f2-a-acondition/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء شرط',
        'menu_name_en' => 'create Acondition',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Acondition&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104631 bfc-',
      ),
      104633 => 
      array (
        'id' => '104633',
        'code' => 'f2-a-acondition/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح شرط',
        'menu_name_en' => 'delete Acondition',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Acondition&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104633 bfc-',
      ),
      104634 => 
      array (
        'id' => '104634',
        'code' => 'f2-a-acondition/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل شرط',
        'menu_name_en' => 'display details of Acondition',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Acondition&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104634 bfc-',
      ),
      104635 => 
      array (
        'id' => '104635',
        'code' => 'f2-a-acondition/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في الشروط',
        'menu_name_en' => 'Aconditions search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Acondition&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104635 bfc-',
      ),
      104636 => 
      array (
        'id' => '104636',
        'code' => 'f2-a-acondition/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الشروط',
        'menu_name_en' => 'Conditions',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Acondition&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104636 bfc-',
      ),
      104638 => 
      array (
        'id' => '104638',
        'code' => 'f2-a-acondition_origin/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء لائحة أوقرار',
        'menu_name_en' => 'create Regulation',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=AconditionOrigin&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104638 bfc-',
      ),
      104640 => 
      array (
        'id' => '104640',
        'code' => 'f2-a-acondition_origin/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح لائحة أوقرار',
        'menu_name_en' => 'delete Regulation',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=AconditionOrigin&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104640 bfc-',
      ),
      104641 => 
      array (
        'id' => '104641',
        'code' => 'f2-a-acondition_origin/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل لائحة أوقرار',
        'menu_name_en' => 'display details of Regulation',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AconditionOrigin&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104641 bfc-',
      ),
      104642 => 
      array (
        'id' => '104642',
        'code' => 'f2-a-acondition_origin/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في القرارات و اللوائح',
        'menu_name_en' => 'Regulations search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=AconditionOrigin&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104642 bfc-',
      ),
      104643 => 
      array (
        'id' => '104643',
        'code' => 'f2-a-acondition_origin/qsearch',
        'level' => '999',
        'menu_name_ar' => 'القرارات و اللوائح',
        'menu_name_en' => 'Regulations',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AconditionOrigin&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104643 bfc-',
      ),
      104645 => 
      array (
        'id' => '104645',
        'code' => 'f2-a-aparameter/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء قيمة معلمة',
        'menu_name_en' => 'create ???? ?????',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Aparameter&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104645 bfc-',
      ),
      104647 => 
      array (
        'id' => '104647',
        'code' => 'f2-a-aparameter/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح قيمة معلمة',
        'menu_name_en' => 'delete ???? ?????',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Aparameter&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104647 bfc-',
      ),
      104648 => 
      array (
        'id' => '104648',
        'code' => 'f2-a-aparameter/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل قيمة معلمة',
        'menu_name_en' => 'display details of ???? ?????',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Aparameter&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104648 bfc-',
      ),
      104649 => 
      array (
        'id' => '104649',
        'code' => 'f2-a-aparameter/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في القيم المعلمة',
        'menu_name_en' => '????? ??????? search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Aparameter&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104649 bfc-',
      ),
      104650 => 
      array (
        'id' => '104650',
        'code' => 'f2-a-aparameter/qsearch',
        'level' => '999',
        'menu_name_ar' => 'القيم المعلمة',
        'menu_name_en' => 'Parameters',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Aparameter&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104650 bfc-',
      ),
      104680 => 
      array (
        'id' => '104680',
        'code' => 'f2-a-academic_year/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء عام دراسي',
        'menu_name_en' => 'create Academic year',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=AcademicYear&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104680 bfc-',
      ),
      104682 => 
      array (
        'id' => '104682',
        'code' => 'f2-a-academic_year/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح عام دراسي',
        'menu_name_en' => 'delete Academic year',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=AcademicYear&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104682 bfc-',
      ),
      104683 => 
      array (
        'id' => '104683',
        'code' => 'f2-a-academic_year/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل عام دراسي',
        'menu_name_en' => 'display details of Academic year',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AcademicYear&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104683 bfc-',
      ),
      104684 => 
      array (
        'id' => '104684',
        'code' => 'f2-a-academic_year/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في السنوات الدراسية',
        'menu_name_en' => 'Academic years search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=AcademicYear&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104684 bfc-',
      ),
      104685 => 
      array (
        'id' => '104685',
        'code' => 'f2-a-academic_year/qsearch',
        'level' => '999',
        'menu_name_ar' => 'السنوات الدراسية',
        'menu_name_en' => 'Academic years',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AcademicYear&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104685 bfc-',
      ),
      104687 => 
      array (
        'id' => '104687',
        'code' => 'f2-a-program_track/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء مسار أكاديمي',
        'menu_name_en' => 'create Program track',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104687 bfc-',
      ),
      104689 => 
      array (
        'id' => '104689',
        'code' => 'f2-a-program_track/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح مسار أكاديمي',
        'menu_name_en' => 'delete Program track',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104689 bfc-',
      ),
      104690 => 
      array (
        'id' => '104690',
        'code' => 'f2-a-program_track/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل مسار أكاديمي',
        'menu_name_en' => 'display details of Program track',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104690 bfc-',
      ),
      104691 => 
      array (
        'id' => '104691',
        'code' => 'f2-a-program_track/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في المسارات الأكاديمية',
        'menu_name_en' => 'Program tracks search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104691 bfc-',
      ),
      104692 => 
      array (
        'id' => '104692',
        'code' => 'f2-a-program_track/qsearch',
        'level' => '999',
        'menu_name_ar' => 'المسارات الأكاديمية',
        'menu_name_en' => 'Program tracks',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104692 bfc-',
      ),
      104694 => 
      array (
        'id' => '104694',
        'code' => 'f2-a-application_model/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء نموذج قبول',
        'menu_name_en' => 'create Application model',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ApplicationModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104694 bfc-',
      ),
      104696 => 
      array (
        'id' => '104696',
        'code' => 'f2-a-application_model/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح نموذج قبول',
        'menu_name_en' => 'delete Application model',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ApplicationModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104696 bfc-',
      ),
      104697 => 
      array (
        'id' => '104697',
        'code' => 'f2-a-application_model/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل نموذج قبول',
        'menu_name_en' => 'display details of Application model',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ApplicationModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104697 bfc-',
      ),
      104698 => 
      array (
        'id' => '104698',
        'code' => 'f2-a-application_model/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في نماذج القبول',
        'menu_name_en' => 'Application models search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ApplicationModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104698 bfc-',
      ),
      104699 => 
      array (
        'id' => '104699',
        'code' => 'f2-a-application_model/qsearch',
        'level' => '999',
        'menu_name_ar' => 'نماذج القبول',
        'menu_name_en' => 'Application models',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ApplicationModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104699 bfc-',
      ),
      104718 => 
      array (
        'id' => '104718',
        'code' => 'f2-a-application_plan/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء خطة تقديم',
        'menu_name_en' => 'create Application plan',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ApplicationPlan&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104718 bfc-',
      ),
      104720 => 
      array (
        'id' => '104720',
        'code' => 'f2-a-application_plan/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح خطة تقديم',
        'menu_name_en' => 'delete Application plan',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ApplicationPlan&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104720 bfc-',
      ),
      104721 => 
      array (
        'id' => '104721',
        'code' => 'f2-a-application_plan/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل خطة تقديم',
        'menu_name_en' => 'display details of Application plan',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ApplicationPlan&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104721 bfc-',
      ),
      104722 => 
      array (
        'id' => '104722',
        'code' => 'f2-a-application_plan/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في خطط التقديم',
        'menu_name_en' => 'Application plans search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ApplicationPlan&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104722 bfc-',
      ),
      104723 => 
      array (
        'id' => '104723',
        'code' => 'f2-a-application_plan/qsearch',
        'level' => '999',
        'menu_name_ar' => 'خطط التقديم',
        'menu_name_en' => 'Application plans',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ApplicationPlan&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104723 bfc-',
      ),
      104788 => 
      array (
        'id' => '104788',
        'code' => 'f2-a-app_model_api/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء خدمة نموذج تقديم',
        'menu_name_en' => 'create ???? ????? ?????',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=AppModelApi&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104788 bfc-',
      ),
      104790 => 
      array (
        'id' => '104790',
        'code' => 'f2-a-app_model_api/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح خدمة نموذج تقديم',
        'menu_name_en' => 'delete ???? ????? ?????',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=AppModelApi&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104790 bfc-',
      ),
      104791 => 
      array (
        'id' => '104791',
        'code' => 'f2-a-app_model_api/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل خدمة نموذج تقديم',
        'menu_name_en' => 'display details of ???? ????? ?????',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AppModelApi&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104791 bfc-',
      ),
      104792 => 
      array (
        'id' => '104792',
        'code' => 'f2-a-app_model_api/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في خدمات نماذج التقديم',
        'menu_name_en' => '????? ????? ??????? search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=AppModelApi&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104792 bfc-',
      ),
      104793 => 
      array (
        'id' => '104793',
        'code' => 'f2-a-app_model_api/qsearch',
        'level' => '999',
        'menu_name_ar' => 'خدمات نماذج التقديم',
        'menu_name_en' => 'App model apis',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AppModelApi&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104793 bfc-',
      ),
      104795 => 
      array (
        'id' => '104795',
        'code' => 'f2-a-api_endpoint/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء خدمة الكترونية',
        'menu_name_en' => 'create ???? ?????????',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ApiEndpoint&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104795 bfc-',
      ),
      104797 => 
      array (
        'id' => '104797',
        'code' => 'f2-a-api_endpoint/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح خدمة الكترونية',
        'menu_name_en' => 'delete ???? ?????????',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ApiEndpoint&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104797 bfc-',
      ),
      104798 => 
      array (
        'id' => '104798',
        'code' => 'f2-a-api_endpoint/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل خدمة الكترونية',
        'menu_name_en' => 'display details of ???? ?????????',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ApiEndpoint&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104798 bfc-',
      ),
      104799 => 
      array (
        'id' => '104799',
        'code' => 'f2-a-api_endpoint/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في الخدمات الاكترونية',
        'menu_name_en' => '??????? ?????????? search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ApiEndpoint&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104799 bfc-',
      ),
      104800 => 
      array (
        'id' => '104800',
        'code' => 'f2-a-api_endpoint/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الخدمات الاكترونية',
        'menu_name_en' => 'Api endpoints',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ApiEndpoint&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104800 bfc-',
      ),
      104802 => 
      array (
        'id' => '104802',
        'code' => 'f2-a-application_field/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء حقل',
        'menu_name_en' => 'create ???',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ApplicationField&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104802 bfc-',
      ),
      104804 => 
      array (
        'id' => '104804',
        'code' => 'f2-a-application_field/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح حقل',
        'menu_name_en' => 'delete ???',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ApplicationField&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104804 bfc-',
      ),
      104805 => 
      array (
        'id' => '104805',
        'code' => 'f2-a-application_field/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل حقل',
        'menu_name_en' => 'display details of ???',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ApplicationField&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104805 bfc-',
      ),
      104806 => 
      array (
        'id' => '104806',
        'code' => 'f2-a-application_field/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في حقول البيانات',
        'menu_name_en' => '???? ???????? search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ApplicationField&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104806 bfc-',
      ),
      104807 => 
      array (
        'id' => '104807',
        'code' => 'f2-a-application_field/qsearch',
        'level' => '999',
        'menu_name_ar' => 'حقول البيانات',
        'menu_name_en' => '???? ????????',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ApplicationField&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104807 bfc-',
      ),
      104810 => 
      array (
        'id' => '104810',
        'code' => 'f2-a-screen_model/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء شاشة ادخال',
        'menu_name_en' => 'create Screen model',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ScreenModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104810 bfc-',
      ),
      104812 => 
      array (
        'id' => '104812',
        'code' => 'f2-a-screen_model/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح شاشة ادخال',
        'menu_name_en' => 'delete Screen model',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ScreenModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104812 bfc-',
      ),
      104813 => 
      array (
        'id' => '104813',
        'code' => 'f2-a-screen_model/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل شاشة ادخال',
        'menu_name_en' => 'display details of Screen model',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ScreenModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104813 bfc-',
      ),
      104814 => 
      array (
        'id' => '104814',
        'code' => 'f2-a-screen_model/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في شاشات الإدخال',
        'menu_name_en' => 'Screen models search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ScreenModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104814 bfc-',
      ),
      104815 => 
      array (
        'id' => '104815',
        'code' => 'f2-a-screen_model/qsearch',
        'level' => '999',
        'menu_name_ar' => 'شاشات الإدخال',
        'menu_name_en' => 'Screen models',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ScreenModel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104815 bfc-',
      ),
    ),
    'sub-folders' => 
    array (
    ),
  ),
);