<?php

	$role_info[384] = array (
  'code' => 'goal-programs',
  'name' => 
  array (
    'ar' => 'البرامج',
    'en' => 'Programs',
  ),
  'menu' => 
  array (
    'need_admin' => false,
    'id' => '384',
    'menu_name_' => 'البرامج',
    'menu_name_ar' => 'البرامج',
    'menu_name_en' => 'Programs',
    'page' => 'main.php?Main_Page=fm.php&a=1282&r=384',
    'css' => 'info',
    'icon' => ' icon-384',
    'showme' => true,
    'items' => 
    array (
      104608 => 
      array (
        'id' => '104608',
        'code' => 'f2-a-academic_level/qsearch',
        'level' => '999',
        'menu_name_ar' => 'المراحل الدراسية',
        'menu_name_en' => 'Academic levels',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AcademicLevel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104608 bfc-',
      ),
      104615 => 
      array (
        'id' => '104615',
        'code' => 'f2-a-degree/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الشهادات',
        'menu_name_en' => 'Degrees',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Degree&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104615 bfc-',
      ),
      104622 => 
      array (
        'id' => '104622',
        'code' => 'f2-a-major/qsearch',
        'level' => '999',
        'menu_name_ar' => 'التخصصات',
        'menu_name_en' => 'Majors',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Major&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104622 bfc-',
      ),
      104678 => 
      array (
        'id' => '104678',
        'code' => 'f2-a-academic_program/qsearch',
        'level' => '999',
        'menu_name_ar' => 'البرامج الدراسية',
        'menu_name_en' => 'Academic programs',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AcademicProgram&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104678 bfc-',
      ),
      104716 => 
      array (
        'id' => '104716',
        'code' => 'f2-a-academic_program_offering/qsearch',
        'level' => '999',
        'menu_name_ar' => 'البرامج المتاحة',
        'menu_name_en' => 'Academic program offerings',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AcademicProgramOffering&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104716 bfc-',
      ),
      104825 => 
      array (
        'id' => '104825',
        'code' => 'f2-a-scholarship/qsearch',
        'level' => '1',
        'menu_name_ar' => 'منح',
        'menu_name_en' => 'Scholarships',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Scholarship&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104825 bfc-',
      ),
      105260 => 
      array (
        'id' => '105260',
        'code' => 'f2-a-program_requirement/qsearch',
        'level' => '1',
        'menu_name_ar' => 'متطلبات البرامج',
        'menu_name_en' => 'Program Requirements',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ProgramRequirement&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-105260 bfc-',
      ),
    ),
    'otherbfs' => 
    array (
      104603 => 
      array (
        'id' => '104603',
        'code' => 'f2-a-academic_level/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء مرحلة اكاديمية',
        'menu_name_en' => 'create Academic level',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=AcademicLevel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104603 bfc-',
      ),
      104605 => 
      array (
        'id' => '104605',
        'code' => 'f2-a-academic_level/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح مرحلة اكاديمية',
        'menu_name_en' => 'delete Academic level',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=AcademicLevel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104605 bfc-',
      ),
      104606 => 
      array (
        'id' => '104606',
        'code' => 'f1-a-tb13865/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل مرحلة اكاديمية',
        'menu_name_en' => 'display details of Academic level',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AcademicLevel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104606 bfc-',
      ),
      104607 => 
      array (
        'id' => '104607',
        'code' => 'f2-a-academic_level/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في المراحل الدراسية',
        'menu_name_en' => 'Academic levels search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=AcademicLevel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104607 bfc-',
      ),
      104608 => 
      array (
        'id' => '104608',
        'code' => 'f2-a-academic_level/qsearch',
        'level' => '999',
        'menu_name_ar' => 'المراحل الدراسية',
        'menu_name_en' => 'Academic levels',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AcademicLevel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104608 bfc-',
      ),
      104610 => 
      array (
        'id' => '104610',
        'code' => 'f2-a-degree/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء شهادة',
        'menu_name_en' => 'create ........',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Degree&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104610 bfc-',
      ),
      104612 => 
      array (
        'id' => '104612',
        'code' => 'f2-a-degree/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح شهادة',
        'menu_name_en' => 'delete ........',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Degree&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104612 bfc-',
      ),
      104613 => 
      array (
        'id' => '104613',
        'code' => 'f2-a-degree/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل شهادة',
        'menu_name_en' => 'display details of ........',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Degree&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104613 bfc-',
      ),
      104614 => 
      array (
        'id' => '104614',
        'code' => 'f2-a-degree/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في الشهادات',
        'menu_name_en' => '........ search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Degree&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104614 bfc-',
      ),
      104615 => 
      array (
        'id' => '104615',
        'code' => 'f2-a-degree/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الشهادات',
        'menu_name_en' => 'Degrees',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Degree&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104615 bfc-',
      ),
      104617 => 
      array (
        'id' => '104617',
        'code' => 'f2-a-major/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء تخصص',
        'menu_name_en' => 'create ........',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Major&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104617 bfc-',
      ),
      104619 => 
      array (
        'id' => '104619',
        'code' => 'f2-a-major/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح تخصص',
        'menu_name_en' => 'delete ........',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Major&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104619 bfc-',
      ),
      104620 => 
      array (
        'id' => '104620',
        'code' => 'f2-a-major/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل تخصص',
        'menu_name_en' => 'display details of ........',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Major&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104620 bfc-',
      ),
      104621 => 
      array (
        'id' => '104621',
        'code' => 'f2-a-major/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في التخصصات',
        'menu_name_en' => '........ search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Major&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104621 bfc-',
      ),
      104622 => 
      array (
        'id' => '104622',
        'code' => 'f2-a-major/qsearch',
        'level' => '999',
        'menu_name_ar' => 'التخصصات',
        'menu_name_en' => 'Majors',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Major&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104622 bfc-',
      ),
      104673 => 
      array (
        'id' => '104673',
        'code' => 'f2-a-academic_program/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء برنامج دراسي',
        'menu_name_en' => 'create Academic program',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=AcademicProgram&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104673 bfc-',
      ),
      104675 => 
      array (
        'id' => '104675',
        'code' => 'f2-a-academic_program/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح برنامج دراسي',
        'menu_name_en' => 'delete Academic program',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=AcademicProgram&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104675 bfc-',
      ),
      104676 => 
      array (
        'id' => '104676',
        'code' => 'f2-a-academic_program/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل برنامج دراسي',
        'menu_name_en' => 'display details of Academic program',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AcademicProgram&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104676 bfc-',
      ),
      104677 => 
      array (
        'id' => '104677',
        'code' => 'f2-a-academic_program/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في البرامج الدراسية',
        'menu_name_en' => 'Academic programs search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=AcademicProgram&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104677 bfc-',
      ),
      104678 => 
      array (
        'id' => '104678',
        'code' => 'f2-a-academic_program/qsearch',
        'level' => '999',
        'menu_name_ar' => 'البرامج الدراسية',
        'menu_name_en' => 'Academic programs',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AcademicProgram&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104678 bfc-',
      ),
      104687 => 
      array (
        'id' => '104687',
        'code' => 'f2-a-program_track/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء مسار أكاديمي',
        'menu_name_en' => 'create Program track',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104687 bfc-',
      ),
      104689 => 
      array (
        'id' => '104689',
        'code' => 'f2-a-program_track/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح مسار أكاديمي',
        'menu_name_en' => 'delete Program track',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104689 bfc-',
      ),
      104690 => 
      array (
        'id' => '104690',
        'code' => 'f2-a-program_track/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل مسار أكاديمي',
        'menu_name_en' => 'display details of Program track',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104690 bfc-',
      ),
      104691 => 
      array (
        'id' => '104691',
        'code' => 'f2-a-program_track/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في المسارات الأكاديمية',
        'menu_name_en' => 'Program tracks search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104691 bfc-',
      ),
      104692 => 
      array (
        'id' => '104692',
        'code' => 'f2-a-program_track/qsearch',
        'level' => '999',
        'menu_name_ar' => 'المسارات الأكاديمية',
        'menu_name_en' => 'Program tracks',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ProgramTrack&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104692 bfc-',
      ),
      104711 => 
      array (
        'id' => '104711',
        'code' => 'f2-a-academic_program_offering/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء برنامج متاح',
        'menu_name_en' => 'create Academic program offering',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=AcademicProgramOffering&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104711 bfc-',
      ),
      104713 => 
      array (
        'id' => '104713',
        'code' => 'f2-a-academic_program_offering/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح برنامج متاح',
        'menu_name_en' => 'delete Academic program offering',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=AcademicProgramOffering&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104713 bfc-',
      ),
      104714 => 
      array (
        'id' => '104714',
        'code' => 'f2-a-academic_program_offering/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل برنامج متاح',
        'menu_name_en' => 'display details of Academic program offering',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AcademicProgramOffering&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104714 bfc-',
      ),
      104715 => 
      array (
        'id' => '104715',
        'code' => 'f2-a-academic_program_offering/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في البرامج المتاحة',
        'menu_name_en' => 'Academic program offerings search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=AcademicProgramOffering&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104715 bfc-',
      ),
      104716 => 
      array (
        'id' => '104716',
        'code' => 'f2-a-academic_program_offering/qsearch',
        'level' => '999',
        'menu_name_ar' => 'البرامج المتاحة',
        'menu_name_en' => 'Academic program offerings',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=AcademicProgramOffering&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104716 bfc-',
      ),
      104817 => 
      array (
        'id' => '104817',
        'code' => 'f2-a-academic_level/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل مرحلة اكاديمية',
        'menu_name_en' => 'display details of Academic level',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=AcademicLevel&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104817 bfc-',
      ),
      104820 => 
      array (
        'id' => '104820',
        'code' => 'f2-a-scholarship/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء منحة',
        'menu_name_en' => 'create Scholarship',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Scholarship&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104820 bfc-',
      ),
      104822 => 
      array (
        'id' => '104822',
        'code' => 'f2-a-scholarship/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح منحة',
        'menu_name_en' => 'delete Scholarship',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Scholarship&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104822 bfc-',
      ),
      104823 => 
      array (
        'id' => '104823',
        'code' => 'f2-a-scholarship/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل منحة',
        'menu_name_en' => 'display details of Scholarship',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Scholarship&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104823 bfc-',
      ),
      104824 => 
      array (
        'id' => '104824',
        'code' => 'f2-a-scholarship/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في منح',
        'menu_name_en' => 'Scholarships search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Scholarship&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104824 bfc-',
      ),
      104825 => 
      array (
        'id' => '104825',
        'code' => 'f2-a-scholarship/qsearch',
        'level' => '1',
        'menu_name_ar' => 'منح',
        'menu_name_en' => 'Scholarships',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Scholarship&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-104825 bfc-',
      ),
      105260 => 
      array (
        'id' => '105260',
        'code' => 'f2-a-program_requirement/qsearch',
        'level' => '1',
        'menu_name_ar' => 'متطلبات البرامج',
        'menu_name_en' => 'Program Requirements',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ProgramRequirement&currmod=adm',
        'css' => 'bf',
        'icon' => 'bficon-105260 bfc-',
      ),
    ),
    'sub-folders' => 
    array (
    ),
  ),
);