<?php
// select concat('if($tu_type == self::$UNIT_',UPPER(training_unit_type_code),') return ',id, '; //', training_unit_typ_name_ar,' - ', training_unit_typ_name_en) as name from training_unit_type;
// select concat('$UNIT_',UPPER(training_unit_type_code),'=',id, ' //', training_unit_typ_name_ar,' - ', training_unit_typ_name_en) as name from training_unit_type;
class TvtcTunitToOrgunit
{

    public static $UNIT_MI=1; //تدريب عسكري مهني - Professional milit...
    public static $UNIT_TC=2; //كلية تقنية - College of Technology
    public static $UNIT_HI=3; //معهد صناعي ثانوي - Secondary industri...
    public static $UNIT_TT=4; //كلية  تقنية تطبيقية - College of appl...
    public static $UNIT_CE=5; //كلية اتصالات وإلكترونيات - College of...
    public static $UNIT_CI=6; //كلية اتصالات ومعلومات - College of Co...
    public static $UNIT_TO=7; //كلية سياحة و فندقة - College of Touri...
    public static $UNIT_PS=8; //معهد تدريب بالسجون - Prison training ...
    public static $UNIT_AR=9; //معهد عمارة وتشييد - Institute of Arch...
    public static $UNIT_CL=10; //مرحلة التكميلي - Complementary stage

    public static function convertTunitTypeToOrgunitType($tu_type)
    {
        if($tu_type == self::$UNIT_MI) return 'institute'; //تدريب عسكري مهني - Professional milit...
        if($tu_type == self::$UNIT_TC) return 'college'; //كلية تقنية - College of Technology
        if($tu_type == self::$UNIT_HI) return 'institute'; //معهد صناعي ثانوي - Secondary industri...
        if($tu_type == self::$UNIT_TT) return 'college'; //كلية  تقنية تطبيقية - College of appl...
        if($tu_type == self::$UNIT_CE) return 'college'; //كلية اتصالات وإلكترونيات - College of...
        if($tu_type == self::$UNIT_CI) return 'college'; //كلية اتصالات ومعلومات - College of Co...
        if($tu_type == self::$UNIT_TO) return 'college'; //كلية سياحة و فندقة - College of Touri...
        if($tu_type == self::$UNIT_PS) return 'institute'; //معهد تدريب بالسجون - Prison training ...
        if($tu_type == self::$UNIT_AR) return 'institute'; //معهد عمارة وتشييد - Institute of Arch...
        if($tu_type == self::$UNIT_CL) return 'institute'; //مرحلة التكميلي - Complementary stage

        return 0;
    }
}

