<?php
$developers = [
    'rafik' => 1,
    'medali' => 2,
];
$migrations = [
    '00001' => ['by'=>'rafik', 'title' => 'first migration test'],
    '00002' => ['by'=>'medali', 'title' => 'admission_agreement_scope'],
    '00003' => ['by'=>'medali', 'title' => 'admission_agreement_plan'],
    '00004' => ['by'=>'medali', 'title' => 'القبول المباشر'],
    '00005' => ['by'=>'medali', 'title' => 'applicant qualification'],
    '00006' => ['by'=>'medali', 'title' => 'Add date to academic level'],
    '00007' => ['by'=>'rafik', 'title' => 'continue work on application conditions'],
    '00008' => ['by'=>'medali', 'title' => ' add training unit type mfk'],
    '00009' => ['by'=>'rafik', 'title' => 'applicant do application'],
    '00010' => ['by'=>'medali', 'title' => 'add imported field to applicant_evaluation'],
    '00011' => ['by'=>'rafik', 'title' => 'applicant tables partionned'],
    '00012' => ['by'=>'rafik', 'title' => 'applicant fields ++'],
    '00013' => ['by'=>'rafik', 'title' => 'application step workflow'],
    '00014' => ['by'=>'medali', 'title' => 'recommendation letter'],
    '00015' => ['by'=>'medali','title'=>'add transaction fees module'],
    '00016' => ['by'=>'rafik','title'=>'level offring and program offring fixed by amjad for TVTC executed'],
    '00017' => ['by'=>'rafik','title'=>'level offring and program offring fixed by amjad for PMU executed'],
    '00018' => ['by'=>'rafik','title'=>'program offring complete readonly calculted fields'],
    '00019' => ['by'=>'medali','title'=>'application payment module change tables name'],
    '00020' => ['by'=>'medali','title'=>'add adm file field to qualification and evaluation'],
    '00021' => ['by'=>'rafik', 'title' => 'bug fixes'],
    '00022' => ['by'=>'medali', 'title' => 'add financial transaction unit'],
    '00023' => ['by'=>'medali', 'title' => 'add scholarship'],
    '00024' => ['by'=>'rafik', 'title' => 'file manager'],
    '00025' => ['by'=>'medali', 'title' => 'manage scholarship'],
    '00026' => ['by'=>'rafik', 'title' => 'files upload management for workflow module'],
    '00027' => ['by'=>'medali', 'title' => 'id in applicant_file auto increment'],
    '00028' => ['by'=>'medali', 'title' => 'faq module'],
    '00029' => ['by'=>'medali', 'title' => 'populate major qualification tables'],
    '00030' => ['by'=>'rafik', 'title' => 'files upload management for applicant'],
    '00031' => ['by'=>'medali', 'title' => 'add instructions table'],
    '00032' => ['by'=>'rafik', 'title' => 'work on UOH needs'],
    '00033' => ['by'=>'rafik', 'title' => 'UOH needed previleges'],
    '00034' => ['by'=>'rafik', 'title' => 'workflow file + other UOH needs'],
    '00035' => ['by'=>'rafik', 'title' => 'prog track new logic and design'],
    '00036' => ['by'=>'rafik', 'title' => 'UOH more previleges'],
    '00037' => ['by'=>'medali', 'title' => 'default value + column password length'],
    '00038' => ['by'=>'rafik', 'title' => 'UOH more customization of settings'],
    '00039' => ['by'=>'medali', 'title' => 'add prospect applicant table'],
    '00040' => ['by'=>'medali', 'title' => 'add prospect qualification table'],
    '00041' => ['by'=>'rafik', 'title' => 'UOH+TVTC more settings'],
    '00042' => ['by'=>'rafik', 'title' => 'Check program track availability & do sorting (farz)'],
    '00043' => ['by'=>'medali', 'title' => 'add column to academic_program'],
    '00044' => ['by'=>'rafik', 'title' => 'UMS and Scope for Admission'],
    '00045' => ['by'=>'medali','title'=>'add educational zone table'],
    '00046' => ['by'=>'rafik', 'title' => 'Farz settings'],
    '00047' => ['by'=>'rafik', 'title' => 'Application simulator'],
    '00048' => ['by'=>'rafik', 'title' => 'Menus & previleges update'],
    '00049' => ['by'=>'rafik', 'title' => 'Farz manager/simulator'],
    '00050' => ['by'=>'rafik', 'title' => 'offline data and sync academic level and program'],
    '00051' => ['by'=>'rafik', 'title' => 'Farz manager/simulator suite ...'],
    '00052' => ['by'=>'medali', 'title' => 'add fields to academic_program'],
    '00053' => ['by'=>'rafik', 'title' => 'Farz manager/simulator suite 2'],
    '00054' => ['by'=>'rafik', 'title' => 'Bug fixes : Can be rexecuted updates even if fail'],
    '00055' => ['by'=>'medali','title'=>'add fields to application step'],
    '00056' => ['by'=>'medali','title'=>'data for program_qualification'],
    '00057' => ['by'=>'rafik', 'title' => 'Farz UOH capacity by Major path'],
    '00058' => ['by'=>'medali','title'=>'add source name to applicant_qualification'],
    '00059' => ['by'=>'medali','title'=>'add field profile_populated to applicant'],
    '00060' => ['by'=>'medali','title'=>'add table relationship'],
    '00061' => ['by'=>'medali','title'=>'create ADMStudentAdmission table'],
    '00062' => ['by'=>'rafik','title'=>'import real data from cloud for developer tests'],
    '00063' => ['by'=>'medali','title'=>'add field to application model'],
    '00064' => ['by'=>'medali','title'=>'add field to academic_level'],
    '00065' => ['by'=>'medali','title'=>'add field to institution'],
    '00066' => ['by'=>'medali','title'=>'contact us'],
    '00067' => ['by'=>'medali','title'=>'applicant_evaluation.need_update'],
    '00068' => ['by'=>'medali','title'=>'service item changes'],
    '00069' => ['by'=>'medali','title'=>'applicant_file.document_type_id + service_request.application_plan_id'],
    '00070' => ['by'=>'rafik','title'=>'sorting screen needs'],
    '00071' => ['by'=>'medali','title'=>'add field to service_request'],
    '00072' => ['by'=>'medali','title'=>'size qualification major name'],
    '00073' => ['by'=>'medali','title'=>'request status insert'],
    '00074' => ['by'=>'medali','title'=>'add simulation tno institution'],
    '00075' => ['by'=>'medali','title'=>'add country to applicant_qualification'],
    '00076' => ['by'=>'rafik','title'=>'make application table partitionned'],
    '00077' => ['by'=>'medali','title'=>'payment module'],
    '00078' => ['by'=>'rafik','title'=>'prepare some features for NAUSS'],
    '00079' => ['by'=>'medali','title'=>'add field to institution'],
    '00080' => ['by'=>'medali','title'=>'add index unique to financial_transaction'],
    '00081' => ['by'=>'medali','title'=>'add grading scale table'],
    '00082' => ['by'=>'medali','title'=>'add academic period table'],
    '00083' => ['by'=>'medali','title'=>'add tuition base table'],
    '00084' => ['by'=>'medali','title'=>'add bridging_semester and bridging_fees to program_qualification'],
    '00085' => ['by'=>'medali','title'=>'target audience changes'],
    '00086' => ['by'=>'medali','title'=>'add field to tuition_base and academic_term'],
    '00087' => ['by'=>'medali','title'=>'sprint 4 nominating module'],
    '00088' => ['by'=>'medali','title'=>'add bridging_fees_comment to program_qualification'],
    '00089' => ['by'=>'medali','title'=>'current period + supp program'],
    '00090' => ['by'=>'rafik','title'=>'prepare demo for NAUSS'],
    '00091' => ['by'=>'medali','title'=>'add to-publish to academic_program'],
    '00092' => ['by'=>'medali','title'=>'add letter_code to nominating_letter'],
    '00093' => ['by'=>'medali','title'=>'add gender_enum'],
    '00094' => ['by'=>'medali','title'=>'add nominating_candidates.country_id'],

    

];

