<?php
$developers = [
    'rafik' => 1,
    'medali' => 2,
];
$migrations = [
    '00001' => ['by'=>'rafik', 'title' => 'first migration test'],
    '00002' => ['by'=>'medali', 'title' => 'admission_agreement_scope'],
    '00003' => ['by'=>'medali', 'title' => 'admission_agreement_plan'],
    '00004' => ['by'=>'medali', 'title' => 'القبول المباشر'],
    '00005' => ['by'=>'medali', 'title' => 'applicant qualification'],
    '00006' => ['by'=>'medali', 'title' => 'Add date to academic level'],
    '00007' => ['by'=>'rafik', 'title' => 'continue work on application conditions'],
    '00008' => ['by'=>'medali', 'title' => ' add training unit type mfk'],
    '00009' => ['by'=>'rafik', 'title' => 'applicant do application'],
    '00010' => ['by'=>'medali', 'title' => 'add imported field to applicant_evaluation'],
    '00011' => ['by'=>'rafik', 'title' => 'applicant tables partionned'],
    '00012' => ['by'=>'rafik', 'title' => 'applicant fields ++'],
    '00013' => ['by'=>'rafik', 'title' => 'application step workflow'],
    '00014' => ['by'=>'medali', 'title' => 'recommendation letter'],
    '00015' => ['by'=>'medali','title'=>'add transaction fees module'],
    '00016' => ['by'=>'rafik','title'=>'level offring and program offring fixed by amjad for TVTC executed'],
    '00017' => ['by'=>'rafik','title'=>'level offring and program offring fixed by amjad for PMU executed'],
    '00018' => ['by'=>'rafik','title'=>'program offring complete readonly calculted fields'],
    '00019' => ['by'=>'medali','title'=>'application payment module change tables name'],
    '00020' => ['by'=>'medali','title'=>'add adm file field to qualification and evaluation'],
    '00021' => ['by'=>'rafik', 'title' => 'bug fixes'],
    '00022' => ['by'=>'medali', 'title' => 'add financial transaction unit'],
    '00023' => ['by'=>'medali', 'title' => 'add scholarship'],
    '00024' => ['by'=>'rafik', 'title' => 'file manager'],
    '00025' => ['by'=>'medali', 'title' => 'manage scholarship'],
    '00026' => ['by'=>'rafik', 'title' => 'files upload management for workflow module'],
    '00027' => ['by'=>'medali', 'title' => 'id in applicant_file auto increment'],
    '00028' => ['by'=>'medali', 'title' => 'faq module'],
    '00029' => ['by'=>'medali', 'title' => 'populate major qualification tables'],
    '00030' => ['by'=>'rafik', 'title' => 'files upload management for applicant'],
    '00031' => ['by'=>'medali', 'title' => 'add instructions table'],
    '00032' => ['by'=>'rafik', 'title' => 'work on UOH needs'],
    '00033' => ['by'=>'rafik', 'title' => 'UOH needed previleges'],
    '00034' => ['by'=>'rafik', 'title' => 'workflow file + other UOH needs'],
    '00035' => ['by'=>'rafik', 'title' => 'prog track new logic and design'],
    '00036' => ['by'=>'rafik', 'title' => 'UOH more previleges'],
    '00037' => ['by'=>'medali', 'title' => 'default value + column password length'],
    '00038' => ['by'=>'rafik', 'title' => 'UOH more customization of settings'],
    '00039' => ['by'=>'medali', 'title' => 'add prospect applicant table'],
    '00040' => ['by'=>'medali', 'title' => 'add prospect qualification table'],
    '00041' => ['by'=>'rafik', 'title' => 'UOH+TVTC more settings'],
    '00042' => ['by'=>'rafik', 'title' => 'Check program track availability & do sorting (farz)'],
    '00043' => ['by'=>'medali', 'title' => 'add column to academic_program'],
    '00044' => ['by'=>'rafik', 'title' => 'UMS and Scope for Admission'],
    '00045' => ['by'=>'medali','title'=>'add educational zone table'],
    '00046' => ['by'=>'rafik', 'title' => 'Farz settings'],
    '00047' => ['by'=>'rafik', 'title' => 'Application simulator'],
    '00048' => ['by'=>'rafik', 'title' => 'Menus & previleges update'],

];

