<?php 

     
        class AdmApplicationCvScoreAfwStructure
        {
                // token separator = §
                public static function initInstance(&$obj)
                {
                        if ($obj instanceof ApplicationCvScore ) 
                        {
                                $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
                                $obj->DISPLAY_FIELD_BY_LANG = ['ar'=>"name_ar", 'en'=>"name_en"];
                                
                                // $obj->ENABLE_DISPLAY_MODE_IN_QEDIT=true;
                                $obj->ORDER_BY_FIELDS = "";
                                 
                                
                                
                                 $obj->UNIQUE_KEY = array('applicant_id', 'application_plan_id','application_simulation_id');
                                $obj->editByStep = true;
                                $obj->editNbSteps = 11;

								$obj->showQeditErrors = true;
								$obj->showRetrieveErrors = true;
								$obj->general_check_errors = true;
                                // $obj->after_save_edit = array("class"=>'ApplicationCvScore',"attribute"=>'xxxx_id', "currmod"=>'adm',"currstep"=>2);
                                $obj->after_save_edit = array("mode"=>"qsearch", "currmod"=>'adm', "class"=>'ApplicationCvScore',"submit"=>true);
                        }
                        else 
                        {
                                ApplicationCvScoreArTranslator::initData();
                                ApplicationCvScoreEnTranslator::initData();
                        }
                }
                
                
                public static $DB_STRUCTURE =  
     array(
                'id' => array('SHOW' => true, 'RETRIEVE' => true, 'EDIT' => false, 'TYPE' => 'PK'),

		
		

		'applicant_id' => array('SHORTNAME' => 'applicant',  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => true,  
				'EDIT' => true,  'QEDIT' => true,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => true,  'UTF8' => false,  
				'TYPE' => 'FK',  'ANSWER' => 'applicant',  'ANSMODULE' => 'adm',  
				'RELATION' => 'unkn',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>1 ),

		'application_plan_id' => array('SHORTNAME' => 'plan',  'SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => true,  
				'EDIT' => true,  'QEDIT' => true,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => true,  'UTF8' => false,  
				'TYPE' => 'FK',  'ANSWER' => 'application_plan',  'ANSMODULE' => 'adm',  
				'RELATION' => 'unkn',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>1 ),

		'application_simulation_id' => array('SHORTNAME' => 'simulation',  'SEARCH' => false,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FK',  'ANSWER' => 'application_simulation',  'ANSMODULE' => 'adm',  
				'RELATION' => 'unkn',  'READONLY' => true,  'DNA' => false, 
				'CSS' => 'width_pct_50','STEP' =>1,'DEFAULT' => '2' ),
		'total_score' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/ 'READONLY' => true,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>1  ),
		'QUALList' => array(
				'STEP' => 2,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'applicant_qualification',
				'ANSMODULE' => 'adm',
				'WHERE' => 'applicant_id=§applicant_id§ ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_100',
		), 
		'QUALGuideList' => array(
				'STEP' => 2,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=1 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',
		), 
		'score_QUAL' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,   'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>2,'CONSTRAINTS' => ['i-between;0,100'],  ),

		'review_date_QUAL' => array('SEARCH' => false,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>2 ),

		'review_comments_QUAL' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>2 ),
		'PEXPList' => array(
			'STEP' => 3,
			'SHOW' => true,
			'FORMAT' => 'retrieve',
			'ICONS' => false,
			'DELETE-ICON' => false,
			'BUTTONS' => false,
			'SEARCH' => false,
			'QSEARCH' => false,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => false,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'FK',
			'CATEGORY' => 'ITEMS',
			'ANSWER' => 'applicant_professional_experience',
			'ANSMODULE' => 'adm',
			'WHERE' => 'applicant_id=§applicant_id§ ',
			'READONLY' => true,
			'CAN-BE-SETTED' => true,
			'CSS' => 'width_pct_100',
		),
		'PEXPGuideList' => array(
				'STEP' => 3,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=2 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',
		), 
		'score_PEXP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>3,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_date_PEXP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>3 ),

		'review_comments_PEXP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>3 ),

		'CRWQList' => array(
				'STEP' => 4,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'applicant_courses',
				'ANSMODULE' => 'adm',
				'WHERE' => 'applicant_id=§applicant_id§ ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_100',
		),
		'CRWQGuideList' => array(
				'STEP' => 4,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=3 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',
		), 
		'score_CRWQ' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>4,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_date_CRWQ' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>4 ),

		'review_comments_CRWQ' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>4 ),

				'SCINTList' => array(
					'STEP' => 5,
					'SHOW' => true,
					'FORMAT' => 'retrieve',
					'ICONS' => false,
					'DELETE-ICON' => false,
					'BUTTONS' => false,
					'SEARCH' => false,
					'QSEARCH' => false,
					'AUDIT' => false,
					'RETRIEVE' => false,
					'EDIT' => false,
					'QEDIT' => false,
					'SIZE' => 32,
					'MAXLENGTH' => 32,
					'MIN-SIZE' => 1,
					'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
					'MANDATORY' => false,
					'UTF8' => false,
					'TYPE' => 'FK',
					'CATEGORY' => 'ITEMS',
					'ANSWER' => 'applicant_membership_scientific_institution',
					'ANSMODULE' => 'adm',
					'WHERE' => 'applicant_id=§applicant_id§ ',
					'READONLY' => true,
					'CAN-BE-SETTED' => true,
					'CSS' => 'width_pct_100',),
		'SCINTGuideList' => array(
				'STEP' => 5,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=4 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',
		),
		'score_SCINT' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>5,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_date_SCINT' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>5 ),

		'review_comments_SCINT' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>5 ),
				
		'VOLACList' => array(
			'STEP' => 6,
			'SHOW' => true,
			'FORMAT' => 'retrieve',
			'ICONS' => false,
			'DELETE-ICON' => false,
			'BUTTONS' => false,
			'SEARCH' => false,
			'QSEARCH' => false,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => false,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'FK',
			'CATEGORY' => 'ITEMS',
			'ANSWER' => 'applicant_volunteer_activity',
			'ANSMODULE' => 'adm',
			'WHERE' => 'applicant_id=§applicant_id§ ',
			'READONLY' => true,
			'CAN-BE-SETTED' => true,
			'CSS' => 'width_pct_100',
		),
		'VOLACGuideList' => array(
				'STEP' => 6,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=5 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',
		),
		'review_date_VOLAC' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>6 ),

		'score_VOLAC' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/ 'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>6,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_comments_VOLAC' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>6 ),
		'AWAPList' => array(
			'STEP' => 7,
			'SHOW' => true,
			'FORMAT' => 'retrieve',
			'ICONS' => false,
			'DELETE-ICON' => false,
			'BUTTONS' => false,
			'SEARCH' => false,
			'QSEARCH' => false,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => false,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'FK',
			'CATEGORY' => 'ITEMS',
			'ANSWER' => 'applicant_certification_appreciation',
			'ANSMODULE' => 'adm',
			'WHERE' => 'applicant_id=§applicant_id§ ',
			'READONLY' => true,
			'CAN-BE-SETTED' => true,
			'CSS' => 'width_pct_100',
		),
		'AWAPGuideList' => array(
				'STEP' => 7,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=6 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',),
		'score_AWAP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/ 'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>7,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_date_AWAP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>7 ),

		'review_comments_AWAP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>7 ),
		'SCRSCList' => array(
			'STEP' => 8,
			'SHOW' => true,
			'FORMAT' => 'retrieve',
			'ICONS' => false,
			'DELETE-ICON' => false,
			'BUTTONS' => false,
			'SEARCH' => false,
			'QSEARCH' => false,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => false,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'FK',
			'CATEGORY' => 'ITEMS',
			'ANSWER' => 'applicant_scientific_research',
			'ANSMODULE' => 'adm',
			'WHERE' => 'applicant_id=§applicant_id§ ',
			'READONLY' => true,
			'CAN-BE-SETTED' => true,
			'CSS' => 'width_pct_100',),
		'SCRSCGuideList' => array(
				'STEP' => 8,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=7 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',),
		'score_SCRSC' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/ 'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>8,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_date_SCRSC' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>8 ),

		'review_comments_SCRSC' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>8 ),
		'LANGPList' => array(
			'STEP' => 9,
			'SHOW' => true,
			'FORMAT' => 'retrieve',
			'ICONS' => false,
			'DELETE-ICON' => false,
			'BUTTONS' => false,
			'SEARCH' => false,
			'QSEARCH' => false,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => false,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'FK',
			'CATEGORY' => 'ITEMS',
			'ANSWER' => 'applicant_language_proficiency',
			'ANSMODULE' => 'adm',
			'WHERE' => 'applicant_id=§applicant_id§ ',
			'READONLY' => true,
			'CAN-BE-SETTED' => true,
			'CSS' => 'width_pct_100',),
			'LANGPGuideList' => array(
				'STEP' => 9,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=8 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',),
		'score_LANGP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/ 'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>9,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_date_LANGP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>9 ),

		'review_comments_LANGP' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>9 ),
		'SCCONFList' => array(
				'STEP' => 10,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'applicant_scientific_conference',
				'ANSMODULE' => 'adm',
				'WHERE' => 'applicant_id=§applicant_id§ ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_100',),
		'SCCONFGuideList' => array(
				'STEP' => 10,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=9 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_75',),
		'score_SCCONF' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/ 'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>10,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_date_SCCONF' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>10 ),

		'review_comments_SCCONF' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT','READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>10 ),
		'RECLTList' => array(
				'STEP' => 11,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'recommendation_letter',
				'ANSMODULE' => 'adm',
				'WHERE' => 'applicant_id=§applicant_id§ ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_100',
		),
		'RECLTGuideList' => array(
				'STEP' => 11,
				'SHOW' => true,
				'FORMAT' => 'retrieve',
				'ICONS' => false,
				'DELETE-ICON' => false,
				'BUTTONS' => false,
				'SEARCH' => false,
				'QSEARCH' => false,
				'AUDIT' => false,
				'RETRIEVE' => false,
				'EDIT' => false,
				'QEDIT' => false,
				'SIZE' => 32,
				'MAXLENGTH' => 32,
				'MIN-SIZE' => 1,
				'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
				'MANDATORY' => false,
				'UTF8' => false,
				'TYPE' => 'FK',
				'CATEGORY' => 'ITEMS',
				'ANSWER' => 'cv_rubric_guide',
				'ANSMODULE' => 'adm',
				'WHERE' => 'cv_rubric_item_id=10 ',
				'READONLY' => true,
				'CAN-BE-SETTED' => true,
				'CSS' => 'width_pct_100',),
		'score_RECLT' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'FLOAT', /*'FORMAT'=>'*.2',*/ 'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>11,'CONSTRAINTS' => ['i-between;0,100'] ),

		'review_date_RECLT' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => false,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => false,  'QEDIT' => false,  
				'SIZE' => 32,  'MAXLENGTH' => 32,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'GDAT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>11 ),

		'review_comments_RECLT' => array('SEARCH' => true,  'QSEARCH' => false,  'SHOW' => true,  'AUDIT' => false,  'RETRIEVE' => false,  
				'EDIT' => true,  'QEDIT' => false,  
				'SIZE' => 200,  'MAXLENGTH' => 200,  'MIN-SIZE' => 1,  'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",  'MANDATORY' => false,  'UTF8' => false,  
				'TYPE' => 'TEXT',  'READONLY' => false,  'DNA' => true, 
				'CSS' => 'width_pct_50','STEP' =>11 ),

                
                'created_by'         => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false,  'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
                'created_at'         => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
                'updated_by'         => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
                'updated_at'         => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
                'validated_by'       => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
                'validated_at'       => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
                'active'             => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),
                'version'            => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),
                'draft'             => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),
                'update_groups_mfk' => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
                'delete_groups_mfk' => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
                'display_groups_mfk' => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
                'sci_id'            => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
                'tech_notes' 	      => array('STEP' =>99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA', "SHOW-ADMIN" => true, 'TOKEN_SEP'=>"§", 'READONLY' =>true, "NO-ERROR-CHECK"=>true, 'FGROUP' => 'tech_fields'),
	);  
    
         }
    


