<?php


class AdmNominatingCandidatesAfwStructure
{
	// token separator = §
	public static function initInstance(&$obj)
	{
		if ($obj instanceof NominatingCandidates) {
			$obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
			$obj->DISPLAY_FIELD_BY_LANG = ['ar' => "name_ar", 'en' => "name_en"];

			// $obj->ENABLE_DISPLAY_MODE_IN_QEDIT=true;
			$obj->ORDER_BY_FIELDS = "";



			$obj->UNIQUE_KEY = array('nomination_letter_id', 'identity_type_id', 'idn');

			$obj->showQeditErrors = true;
			$obj->showRetrieveErrors = true;
			$obj->general_check_errors = true;

			$obj->editByStep = true;
			$obj->editNbSteps = 6;
			$obj->after_save_edit = array("class"=>'NominationLetter',"attribute"=>'nomination_letter_id', "currmod"=>'adm', "currstep"=>2);
			// $obj->after_save_edit = array("mode" => "qsearch", "currmod" => 'adm', "class" => 'NominatingCandidates', "submit" => true);
		} else {
			NominatingCandidatesArTranslator::initData();
			NominatingCandidatesEnTranslator::initData();
		}
	}


	public static $DB_STRUCTURE =
	array(
		'id' => array('SHOW' => true, 'RETRIEVE' => true, 'EDIT' => false, 'TYPE' => 'PK'),


		'nomination_letter_id' => array(
			'SHORTNAME' => 'funding_status',
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'nomination_letter',
			'ANSMODULE' => 'adm',
			'RELATION' => 'OneToMany',
			'READONLY' => true,
			'MANDATORY' => true,
			'DNA' => true,
			'CSS' => 'width_pct_50',
			'STEP' => 1,
		),

		'identity_type_id' => array(
			'SHORTNAME' => 'type',
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => true,
			'EDIT' => true,
			'EDIT_IF_EMPTY' => true,
			'QEDIT' => true,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'identity_type',
			'ANSMODULE' => 'adm',
			'RELATION' => 'unkn',
			'READONLY' => true,
			'MANDATORY' => true,
			'DNA' => true,
			'CSS' => 'width_pct_25',
			'STEP' => 1,
		),

		'idn' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => true,
			'EDIT' => true,
			'EDIT_IF_EMPTY' => true,
			'QEDIT' => true,
			'SIZE' => 40,
			'MAXLENGTH' => 40,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => true,
			'MANDATORY' => true,
			'DNA' => true,
			'CSS' => 'width_pct_25',
			'STEP' => 1,
		),

		'application_plan_id' => array(
			'STEP' => 2,
			'SHORTNAME' => 'plan',
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'application_plan',
			'ANSMODULE' => 'adm',
			'RELATION' => 'ManyToOne',
			'READONLY' => true,
			'MANDATORY' => true,
			'DNA' => true,
			'CSS' => 'width_pct_50',
		),

		'application_simulation_id' => array(
			'IMPORTANT' => 'IN',
			'STEP' => 2,
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SHOW-ADMIN' => true,
			'EDIT-ADMIN' => true,
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'application_simulation',
			'ANSMODULE' => 'adm',
			'SIZE' => 40,
			'DEFAUT' => 1,
			'DISPLAY' => true,
			'RELATION' => 'ManyToOne',
			'MANDATORY' => true,
			'AUTOCOMPLETE' => false,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'READONLY' => true,
			'CSS' => 'width_pct_50',
		),


		

		'first_name_ar' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => true,
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),

		'second_name_ar' => array(
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => true,
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'DNA' => true,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),

		'third_name_ar' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => true,
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'DNA' => true,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),

		'last_name_ar' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => true,
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),

		'first_name_en' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 48,
			'MAXLENGTH' => 48,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => true,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),

		'second_name_en' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 48,
			'MAXLENGTH' => 48,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => true,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'DNA' => true,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),

		'third_name_en' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 48,
			'MAXLENGTH' => 48,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => true,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'DNA' => true,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),

		'last_name_en' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 48,
			'MAXLENGTH' => 48,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => true,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),


		'gender_enum' => array(
			'IMPORTANT' => 'IN',
			'SEARCH' => true,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => true,
			'QSEARCH' => true,
			'SHOW-ADMIN' => true,
			'EDIT-ADMIN' => true,
			'UTF8' => false,
			'TYPE' => 'ENUM',
			'ANSWER' => 'FUNCTION',
			'SIZE' => 40,
			'DEFAUT' => 0,
			'DISPLAY' => true,
			'STEP' => 2,
			'MANDATORY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_25',
		),

/***************************************/

                'qualification_id' => array(
                        'IMPORTANT' => 'HIGH',
                        'SEARCH' => true,
                        'QSEARCH' => true,
                        'SHOW' => true,
                        'RETRIEVE' => true,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'SHOW-ADMIN' => true,
                        'EDIT-ADMIN' => true,
                        'UTF8' => false,
                        'TYPE' => 'FK',
                        'ANSWER' => 'qualification',
                        'ANSMODULE' => 'adm',
                        'SIZE' => 40,
                        'DEFAUT' => 0,
                        'DISPLAY' => true,
                        'STEP' => 3,
                        'RELATION' => 'ManyToOne',
                        'MANDATORY' => true,
                        'READONLY' => false,
                        'AUTOCOMPLETE' => false,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'DEPENDENT_OFME' => array("major_category_id", "source", "qualification_major_id"),
                        'CSS' => 'width_pct_50',
                ),

                /*'level_enum' => array(
                        'IMPORTANT' => 'HIGH',
                        'CATEGORY' => 'SHORTCUT',
                        'SHORTCUT' => 'qualification_id.level_enum',
                        'TYPE' => 'ENUM',
                        'ANSWER' => 'FUNCTION',
                        'SIZE' => 40,
                        'DEFAUT' => 0,
                        'STEP' => 99,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'CSS' => 'width_pct_25',
                ),*/

                // dependecy bring only ctegories that exists in major_path for this qualification_id   
                // done by medali     
                'major_category_id' => array(
                        'IMPORTANT' => 'HIGH',
                        'SEARCH' => true,
                        'QSEARCH' => true,
                        'SHOW' => true,
                        'RETRIEVE' => true,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'SHOW-ADMIN' => true,
                        'EDIT-ADMIN' => true,
                        'UTF8' => false,
                        'TYPE' => 'FK',
                        'ANSWER' => 'major_category',
                        'ANSMODULE' => 'adm',
                        'SIZE' => 40,
                        'DEFAUT' => 0,
                        'DISPLAY' => true,
                        'STEP' => 3,
                        'RELATION' => 'ManyToOne',
                        'MANDATORY' => true,
                        'READONLY' => false,
                        'AUTOCOMPLETE' => false,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'WHERE' => 'id in (select major_category_id from §DBPREFIX§adm.major_path where qualification_id=§qualification_id§ and active="Y")',
                        'DEPENDENCIES' => ['qualification_id'],
                        'DEPENDENT_OFME' => array("qualification_major_id"),
                        'CSS' => 'width_pct_50',
                ),


                'major_path_id' => array(
                        'IMPORTANT' => 'HIGH',
                        'SEARCH' => false,
                        'QSEARCH' => false,
                        'SHOW' => false,
                        'RETRIEVE' => false,
                        'EDIT' => false,
                        'QEDIT' => false,
                        'UTF8' => false,
                        'TYPE' => 'FK',
                        'ANSWER' => 'major_path',
                        'ANSMODULE' => 'adm',
                        'SIZE' => 40,
                        'DEFAUT' => 0,
                        'DISPLAY' => false,
                        'STEP' => 3,
                        'RELATION' => 'ManyToOne',
                        'MANDATORY' => true,
                        'READONLY' => false,
                        'AUTOCOMPLETE' => false,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'CSS' => 'width_pct_50',
                ),

                // @todo  rafik dependency with major_category_id
                'qualification_major_id' => array(
                        'IMPORTANT' => 'HIGH',
                        'SEARCH' => true,
                        'QSEARCH' => true,
                        'SHOW' => true,
                        'RETRIEVE' => true,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'SHOW-ADMIN' => true,
                        'EDIT-ADMIN' => true,
                        'UTF8' => false,
                        'TYPE' => 'FK',
                        'ANSWER' => 'qualification_major',
                        'ANSMODULE' => 'adm',
                        'SIZE' => 40,
                        'DEFAUT' => 0,
                        'DISPLAY' => true,
                        'STEP' => 3,
                        'RELATION' => 'ManyToOne',
                        'MANDATORY' => false,
                        'READONLY' => false,
                        'AUTOCOMPLETE' => false,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'WHERE' => ' id in (select qualification_major_id from §DBPREFIX§adm.qual_major_path mp inner join §DBPREFIX§adm.major_path m on mp.major_path_id=m.id where m.qualification_id=§qualification_id§ and m.major_category_id=§major_category_id§)',
                        'DEPENDENCIES' => ['qualification_id', 'major_category_id'],
                        'DEPENDENT_OFME' => array(),
                        'CSS' => 'width_pct_50',
                ),


                'gpa' => array(
                        'IMPORTANT' => 'HIGH',
                        'SHOW' => true,
                        'RETRIEVE' => true,
                        'QEDIT' => true,
                        'EDIT' => true,
                        'SIZE' => 32,
                        'TYPE' => 'FLOAT', 'FORMAT' => '*.2',
                        'MANDATORY' => true,
                        'STEP' => 3,
                        'DISPLAY' => true,
                        'EDIT-UGROUPS' => '',
                        'CSS' => 'width_pct_25',
                ),

                

                'gpa_from' => array(
                        'IMPORTANT' => 'HIGH',
                        'SHOW' => true,
                        'RETRIEVE' => true,
                        'QEDIT' => true,
                        'EDIT' => true,
                        'TYPE' => 'INT',
                        'MANDATORY' => false,
                        'STEP' => 3,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'READONLY' => false,
                        'DISPLAY' => true,
                        'DEFAUT' => '',
                        'CSS' => 'width_pct_25'
                ),



                'date' => [
                        'IMPORTANT' => 'HIGH',
                        'SEARCH' => true,
                        'SHOW' => true,
                        'DISPLAY' => true,
                        'RETRIEVE' => true,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'MANDATORY' => true,
                        'SEARCH-ADMIN' => true,
                        'SHOW-ADMIN' => true,
                        'EDIT-ADMIN' => true,
                        'UTF8' => false,
                        'TYPE' => 'GDAT',
                        'STEP' => 3,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'DEFAUT' => '',
                        'CSS' => 'width_pct_25',
                ],

                'adm_file_id' => array(
                        'STEP' => 3,
                        'SHORTNAME' => 'workflow_file',
                        'SEARCH' => true,
                        'QSEARCH' => true,
                        'SHOW' => true,
                        'AUDIT' => false,
                        'RETRIEVE' => true,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'SIZE' => 40,
                        'MAXLENGTH' => 32,
                        'DEFAUT' => 0,
                        'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
                        'UTF8' => false,
                        'TYPE' => 'FK',
                        'ANSWER' => 'workflow_file',
                        'WHERE' => 'id in (select workflow_file_id from §DBPREFIX§adm.applicant_file where applicant_id = §applicant_id§ and doc_type_id = 6)', // DOC_TYPE_DIPLOMA = 6
                        'ANSMODULE' => 'workflow',
                        'RELATION' => 'ManyToOne',
                        'READONLY' => true,
                        'CSS' => 'width_pct_50',
                ),

                'country_id' => array(
                        'IMPORTANT' => 'IN',
                        'SEARCH' => true,
                        'QSEARCH' => true,
                        'SHOW' => true,
                        'RETRIEVE' => false,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'SHOW-ADMIN' => true,
                        'EDIT-ADMIN' => true,
                        'UTF8' => false,
                        'TYPE' => 'FK',
                        'ANSWER' => 'country',
                        'ANSMODULE' => 'ums',
                        'SIZE' => 40,
                        'DEFAUT' => 0,
                        'DISPLAY' => true,
                        'STEP' => 3,
                        'RELATION' => 'ManyToOne',
                        'MANDATORY' => true,
                        'READONLY' => false,
                        'AUTOCOMPLETE' => false,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'CSS' => 'width_pct_50',
                                                ),
				'grading_scale_id' => array(
                        'IMPORTANT' => 'IN',
                        'SEARCH' => true,
                        'QSEARCH' => true,
                        'SHOW' => true,
                        'RETRIEVE' => true,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'SHOW-ADMIN' => true,
                        'EDIT-ADMIN' => true,
                        'UTF8' => false,
                        'TYPE' => 'FK',
                        'ANSWER' => 'grading_scale',
                        'ANSMODULE' => 'adm',
                        'SIZE' => 40,
                        'DEFAUT' => 0,
                        'DISPLAY' => true,
                        'STEP' => 3,
                        'RELATION' => 'ManyToOne',
                        'MANDATORY' => false,
                        'READONLY' => false,
                        'AUTOCOMPLETE' => false,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'CSS' => 'width_pct_50',
                                                ),



/****************************************/


		'candidateFullName' => array(
			'IMPORTANT' => 'IN',
			'SEARCH' => false,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => false,
			'QEDIT' => false,
			'SHOW-ADMIN' => true,
			'EDIT-ADMIN' => false,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			"CATEGORY" => "FORMULA",
			'ANSMODULE' => 'adm',
			'SIZE' => 40,
			'DEFAUT' => 0,
			'DISPLAY' => true,
			'STEP' => 6,
			'RELATION' => 'ManyToOne-OneToMany',
			'MANDATORY' => false,
			'READONLY' => true,
			'AUTOCOMPLETE' => true,
			'AUTOCOMPLETE-SEARCH' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_25',
			'HIDE_IF_NEW' => true
		),

		'academic_program_id' => array(
			'SHORTNAME' => 'program',
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'academic_program',
			'ANSMODULE' => 'adm',
			'RELATION' => 'unkn',
			'READONLY' => false,
			'DNA' => true,
			'CSS' => 'width_pct_50',
			'STEP' => 6,
		),


		'email' => array(
			'SEARCH' => false,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'FORMAT' => 'EMAIL',
			'UTF8' => false,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'DNA' => true,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),

		'mobile' => array(
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => true,
			'SIZE' => 25,
			'MAXLENGTH' => 25,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => true,
			'TYPE' => 'TEXT',
			'READONLY' => false,
			'CSS' => 'width_pct_25',
			'STEP' => 2,
		),


		'country_id' => array(
			//'FGROUP' => 'idn-infos',
			//'IMPORTANT' => 'IN',
			'SEARCH' => true,
			'QSEARCH' => true,
			'RETRIEVE' => true,
			'SHOW' => true,
			'EDIT' => true,
			'QEDIT' => true,

			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'country',
			'ANSMODULE' => 'ums',
			'SIZE' => 40,
			//'DEFAUT' => 183,
			//'READONLY-AFTER-INSERT' => true,
			'DISPLAY' => true,
			'STEP' => 2,
			'RELATION' => 'ManyToOne',
			'MANDATORY' => true,
			'AUTOCOMPLETE' => false,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_25',
		),

		'study_funding_status_id' => array(
			'SHORTNAME' => 'funding_status',
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'study_funding_status',
			'ANSMODULE' => 'adm',
			'RELATION' => 'unkn',
			'READONLY' => false,
			'DNA' => true,
			'CSS' => 'width_pct_25',
			'STEP' => 6,
		),


		'track_overpass' => array(
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => true,
			'DEFAUT' => 'N',
			'TYPE' => 'YN',
			'FORMAT' => 'icon',
			'STEP' => 6,
			'READONLY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_25',
		),

		'track_overpass_user_id' => array(
			'SHORTNAME' => 'program',
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'auser',
			'ANSMODULE' => 'ums',
			'RELATION' => 'ManyToOne',
			'READONLY' => true,
			'DNA' => true,
			'CSS' => 'width_pct_50',
			'STEP' => 6,
		),

		'track_overpass_gdate' => [
                        'IMPORTANT' => 'IN',
                        'SEARCH' => true,
                        'SHOW' => true,
                        'DISPLAY' => true,
                        'RETRIEVE' => false,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'SEARCH-ADMIN' => true,
                        'SHOW-ADMIN' => true,
                        'EDIT-ADMIN' => true,
                        'UTF8' => false,
                        'TYPE' => 'GDATE',
                        'FORMAT' => 'DATE',
                        'STEP' => 6,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'MANDATORY' => false,
						'READONLY' => true,
                        'CSS' => 'width_pct_25',
        		],


		'rating_overpass' => array(
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => true,
			'DEFAUT' => 'N',
			'TYPE' => 'YN',
			'FORMAT' => 'icon',
			'STEP' => 6,
			'READONLY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_25',
		),

		'rating_overpass_user_id' => array(
			'SHORTNAME' => 'program',
			'SEARCH' => true,
			'QSEARCH' => false,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => true,
			'QEDIT' => false,
			'SIZE' => 32,
			'MAXLENGTH' => 32,
			'MIN-SIZE' => 1,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'auser',
			'ANSMODULE' => 'ums',
			'RELATION' => 'ManyToOne',
			'READONLY' => true,
			'DNA' => true,
			'CSS' => 'width_pct_50',
			'STEP' => 6,
		),

		'rating_overpass_gdate' => [
                        'IMPORTANT' => 'IN',
                        'SEARCH' => true,
                        'SHOW' => true,
                        'DISPLAY' => true,
                        'RETRIEVE' => false,
                        'EDIT' => true,
                        'QEDIT' => true,
                        'SEARCH-ADMIN' => true,
                        'SHOW-ADMIN' => true,
                        'EDIT-ADMIN' => true,
                        'UTF8' => false,
                        'TYPE' => 'GDATE',
                        'FORMAT' => 'DATE',
                        'STEP' => 2,
                        'DISPLAY-UGROUPS' => '',
                        'EDIT-UGROUPS' => '',
                        'MANDATORY' => false,
						'READONLY' => true,
                        'CSS' => 'width_pct_25',
        		],		

		'applicant_id' => array(
			'STEP' => 6,
			'SHORTNAME' => 'applicant',
			'SEARCH' => true,
			'QSEARCH' => true,
			'SHOW' => true,
			'AUDIT' => false,
			'RETRIEVE' => false,
			'EDIT' => false,
			'QEDIT' => false,
			'SIZE' => 40,
			'MAXLENGTH' => 32,
			'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
			'MANDATORY' => false,
			'UTF8' => false,
			'TYPE' => 'FK',
			'ANSWER' => 'applicant',
			'ANSMODULE' => 'adm',
			'AUTOCOMPLETE' => true,
			'AUTOCOMPLETE-SEARCH' => true,
			'RELATION' => 'OneToOne',
			'READONLY' => false,
			'CSS' => 'width_pct_25',
		),

		'applicantLink' => array(
			'IMPORTANT' => 'IN',
			'SEARCH' => false,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => false,
			'SHOW-ADMIN' => true,
			'EDIT-ADMIN' => true,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			"CATEGORY" => "FORMULA",
			'SIZE' => 40,
			'DEFAUT' => 0,
			'DISPLAY' => true,
			'STEP' => 6,
			'MANDATORY' => false,
			'READONLY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_25',
			'HIDE_IF_NEW' => true
		),

		'myApplicationLink' => array(
			'IMPORTANT' => 'IN',
			'SEARCH' => false,
			'QSEARCH' => false,
			'SHOW' => true,
			'RETRIEVE' => true,
			'EDIT' => true,
			'QEDIT' => false,
			'SHOW-ADMIN' => true,
			'EDIT-ADMIN' => true,
			'UTF8' => false,
			'TYPE' => 'TEXT',
			"CATEGORY" => "FORMULA",
			'SIZE' => 40,
			'DEFAUT' => 0,
			'DISPLAY' => true,
			'STEP' => 6,
			'MANDATORY' => false,
			'READONLY' => true,
			'DISPLAY-UGROUPS' => '',
			'EDIT-UGROUPS' => '',
			'CSS' => 'width_pct_25',
			'HIDE_IF_NEW' => true
		),

		

		'created_by'         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false,  'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
		'created_at'         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
		'updated_by'         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
		'updated_at'         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
		'validated_by'       => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
		'validated_at'       => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
		'active'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),
		'version'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),
		'draft'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),
		'update_groups_mfk' => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		'delete_groups_mfk' => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		'display_groups_mfk' => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
		'sci_id'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
		'tech_notes' 	      => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA', "SHOW-ADMIN" => true, 'TOKEN_SEP' => "§", 'READONLY' => true, "NO-ERROR-CHECK" => true, 'FGROUP' => 'tech_fields'),
	);
}
    


// errors 
